# FastAPI from Frictionless Demo

In [28]:
from morpc.logs import config_logs
import fastapifromfrictionless
import frictionless
import os

In [29]:
config_logs('sensor_tracking.log', 'debug')

2026-03-12 12:56:13,583 | INFO | morpc.logs.config_logs: Set up logging save to file "sensor_tracking.log", log level "debug"

## Create some schemas

Foreign keys define one-to-many relationships. 

Link tables define many-to-many relationships.

#### Deployments
```{literalinclude} data/deployment.schema.yaml
```

#### Sensors
```{literalinclude} data/sensor.schema.yaml
```

#### Locations
```{literalinclude} data/location.schema.yaml
```

#### Contacts
```{literalinclude} data/contact.schema.yaml
```

#### Hotspots
```{literalinclude} data/hotspot.schema.yaml
```

#### Senor Notes
```{literalinclude} data/sensor-note.schema.yaml
```

#### Registrations
```{literalinclude} data/registration.schema.yaml
```

### Links between deployments and contacts
```{literalinclude} data/link-deployment-contact.schema.yaml
```

## Create model.py, app.py, database.py files for sqlmodel and fastapi

In [30]:
fastapifromfrictionless.models('data').build().save('models.py')

2026-03-12 12:56:15,713 | INFO | fastapifromfrictionless.model.__init__: Building models for schemas from data: location.schema.yaml .hotspot.schema.yaml .sensor.schema.yaml .registration.schema.yaml .deployment-note.schema.yaml .sensor-note.schema.yaml .contact.schema.yaml .deployment.schema.yaml
2026-03-12 12:56:15,714 | INFO | fastapifromfrictionless.model.models.data.build: Building model for location.schema.yaml
2026-03-12 12:56:15,723 | INFO | fastapifromfrictionless.model.models.data.build_model: Schema Location foreign keys []
2026-03-12 12:56:15,733 | DEBUG | fastapifromfrictionless.model.models.data.build_model: Location not reference by Registration
2026-03-12 12:56:15,736 | DEBUG | fastapifromfrictionless.model.models.data.build_model: Location not reference by DeploymentNote
2026-03-12 12:56:15,739 | DEBUG | fastapifromfrictionless.model.models.data.build_model: Location not reference by SensorNote
2026-03-12 12:56:15,745 | DEBUG | fastapifromfrictionless.model.models.data.build_model: Location not reference by Deployment
2026-03-12 12:56:15,746 | DEBUG | fastapifromfrictionless.model.models.data.build_model: Location is referenced by Deployment
2026-03-12 12:56:15,747 | DEBUG | fastapifromfrictionless.model.models.data.build_model: Location not reference by Deployment
2026-03-12 12:56:15,748 | DEBUG | fastapifromfrictionless.model.models.data.build_model: Location not reference by Deployment
2026-03-12 12:56:15,749 | INFO | fastapifromfrictionless.model.models.data.build_model: Location is referenced by ['Deployment']
2026-03-12 12:56:15,749 | INFO | fastapifromfrictionless.model.models.data.build_model: {'name': 'address', 'type': 'string', 'constraints': {'required': True}} converted to address: str = Field(primary_key = True)
2026-03-12 12:56:15,750 | INFO | fastapifromfrictionless.model.models.data.build_model: {'name': 'zipcode', 'type': 'integer', 'constraints': {'required': True}} converted to zipcode: int
2026-03-12 12:56:15,751 | INFO | fastapifromfrictionless.model.models.data.build_model: {'name': 'description', 'type': 'string', 'constraints': {'required': True}} converted to description: str
2026-03-12 12:56:15,751 | INFO | fastapifromfrictionless.model.models.data.build_model: {'name': 'neighborhood', 'type': 'string', 'constraints': {'required': True}} converted to neighborhood: str
2026-03-12 12:56:15,752 | INFO | fastapifromfrictionless.model.models.data.build_model: {'name': 'latitude', 'type': 'number', 'constraints': {'required': True}} converted to latitude: float
2026-03-12 12:56:15,753 | INFO | fastapifromfrictionless.model.models.data.build_model: {'name': 'longitude', 'type': 'number', 'constraints': {'required': True}} converted to longitude: float
2026-03-12 12:56:15,753 | DEBUG | fastapifromfrictionless.model.models.data.build_model: class LocationBase(SQLModel):
    address: str = Field(primary_key = True)
    zipcode: int
    description: str
    neighborhood: str
    latitude: float
    longitude: float

2026-03-12 12:56:15,754 | INFO | fastapifromfrictionless.model.models.data.build_model: class Location(LocationBase, TimestampMixin, table=True):
    deployments: list['Deployment'] | None = Relationship(back_populates='locations')

2026-03-12 12:56:15,754 | DEBUG | fastapifromfrictionless.model.models.data.build_model: class LocationCreate(LocationBase):
    pass

2026-03-12 12:56:15,755 | DEBUG | fastapifromfrictionless.model.models.data.build_model: class LocationUpdate(LocationBase):
    address: str | None
    zipcode: int | None
    description: str | None
    neighborhood: str | None
    latitude: float | None
    longitude: float | None

2026-03-12 12:56:15,755 | DEBUG | fastapifromfrictionless.model.models.data.build_model: class LocationPublic(LocationBase):
    created_at: datetime
    updated_at: datetime

2026-03-12 12:56:15,755 | DEBUG | fastapifromfrictionless.model.models.data.build_model: class LocationPublicWithAll(LocationPublic):
    deployments: List['DeploymentPublic'] | None = None

2026-03-12 12:56:15,756 | INFO | fastapifromfrictionless.model.models.data.build: Building model for hotspot.schema.yaml

2026-03-12 12:56:15,760 | INFO | fastapifromfrictionless.model.models.data.build_model: Schema Hotspot foreign keys []
2026-03-12 12:56:15,769 | DEBUG | fastapifromfrictionless.model.models.data.build_model: Hotspot not reference by Registration
2026-03-12 12:56:15,773 | DEBUG | fastapifromfrictionless.model.models.data.build_model: Hotspot not reference by DeploymentNote
2026-03-12 12:56:15,777 | DEBUG | fastapifromfrictionless.model.models.data.build_model: Hotspot not reference by SensorNote
2026-03-12 12:56:15,783 | DEBUG | fastapifromfrictionless.model.models.data.build_model: Hotspot not reference by Deployment
2026-03-12 12:56:15,784 | DEBUG | fastapifromfrictionless.model.models.data.build_model: Hotspot not reference by Deployment
2026-03-12 12:56:15,786 | DEBUG | fastapifromfrictionless.model.models.data.build_model: Hotspot is referenced by Deployment
2026-03-12 12:56:15,786 | DEBUG | fastapifromfrictionless.model.models.data.build_model: Hotspot not reference by Deployment
2026-03-12 12:56:15,787 | INFO | fastapifromfrictionless.model.models.data.build_model: Hotspot is referenced by ['Deployment']
2026-03-12 12:56:15,788 | INFO | fastapifromfrictionless.model.models.data.build_model: {'name': 'macaddr', 'type': 'string', 'constraints': {'required': True}} converted to macaddr: str = Field(primary_key = True)
2026-03-12 12:56:15,789 | INFO | fastapifromfrictionless.model.models.data.build_model: {'name': 'serialnum', 'type': 'string', 'constraints': {'required': True}} converted to serialnum: str
2026-03-12 12:56:15,791 | INFO | fastapifromfrictionless.model.models.data.build_model: {'name': 'status', 'type': 'string', 'constraints': {'required': True}} converted to status: str
2026-03-12 12:56:15,792 | INFO | fastapifromfrictionless.model.models.data.build_model: {'name': 'ssid', 'type': 'string', 'constraints': {'required': True}} converted to ssid: str
2026-03-12 12:56:15,793 | INFO | fastapifromfrictionless.model.models.data.build_model: {'name': 'password', 'type': 'string', 'constraints': {'required': True}} converted to password: str
2026-03-12 12:56:15,794 | DEBUG | fastapifromfrictionless.model.models.data.build_model: class HotspotBase(SQLModel):
    macaddr: str = Field(primary_key = True)
    serialnum: str
    status: str
    ssid: str
    password: str

2026-03-12 12:56:15,795 | INFO | fastapifromfrictionless.model.models.data.build_model: class Hotspot(HotspotBase, TimestampMixin, table=True):
    deployments: list['Deployment'] | None = Relationship(back_populates='hotspots')

2026-03-12 12:56:15,796 | DEBUG | fastapifromfrictionless.model.models.data.build_model: class HotspotCreate(HotspotBase):
    pass

2026-03-12 12:56:15,797 | DEBUG | fastapifromfrictionless.model.models.data.build_model: class HotspotUpdate(HotspotBase):
    macaddr: str | None
    serialnum: str | None
    status: str | None
    ssid: str | None
    password: str | None

2026-03-12 12:56:15,798 | DEBUG | fastapifromfrictionless.model.models.data.build_model: class HotspotPublic(HotspotBase):
    created_at: datetime
    updated_at: datetime

2026-03-12 12:56:15,799 | DEBUG | fastapifromfrictionless.model.models.data.build_model: class HotspotPublicWithAll(HotspotPublic):
    deployments: List['DeploymentPublic'] | None = None

2026-03-12 12:56:15,800 | INFO | fastapifromfrictionless.model.models.data.build: Building model for sensor.schema.yaml
2026-03-12 12:56:15,803 | INFO | fastapifromfrictionless.model.models.data.build_model: Schema Sensor foreign keys []
2026-03-12 12:56:15,816 | DEBUG | fastapifromfrictionless.model.models.data.build_model: Sensor is referenced by Registration
2026-03-12 12:56:15,820 | DEBUG | fastapifromfrictionless.model.models.data.build_model: Sensor not reference by DeploymentNote
2026-03-12 12:56:15,823 | DEBUG | fastapifromfrictionless.model.models.data.build_model: Sensor is referenced by SensorNote
2026-03-12 12:56:15,831 | DEBUG | fastapifromfrictionless.model.models.data.build_model: Sensor is referenced by Deployment
2026-03-12 12:56:15,831 | DEBUG | fastapifromfrictionless.model.models.data.build_model: Sensor not reference by Deployment
2026-03-12 12:56:15,832 | DEBUG | fastapifromfrictionless.model.models.data.build_model: Sensor not reference by Deployment
2026-03-12 12:56:15,832 | DEBUG | fastapifromfrictionless.model.models.data.build_model: Sensor not reference by Deployment
2026-03-12 12:56:15,833 | INFO | fastapifromfrictionless.model.models.data.build_model: Sensor is referenced by ['Registration', 'SensorNote', 'Deployment']
2026-03-12 12:56:15,834 | INFO | fastapifromfrictionless.model.models.data.build_model: {'name': 'macaddr', 'type': 'string', 'constraints': {'required': True}} converted to macaddr: str = Field(primary_key = True)
2026-03-12 12:56:15,834 | INFO | fastapifromfrictionless.model.models.data.build_model: {'name': 'name', 'type': 'string', 'constraints': {'required': True}} converted to name: str
2026-03-12 12:56:15,835 | INFO | fastapifromfrictionless.model.models.data.build_model: {'name': 'type', 'type': 'string'} converted to type: str | None
2026-03-12 12:56:15,836 | INFO | fastapifromfrictionless.model.models.data.build_model: {'name': 'status', 'type': 'string'} converted to status: str | None
2026-03-12 12:56:15,837 | DEBUG | fastapifromfrictionless.model.models.data.build_model: class SensorBase(SQLModel):
    macaddr: str = Field(primary_key = True)
    name: str
    type: str | None
    status: str | None

2026-03-12 12:56:15,838 | INFO | fastapifromfrictionless.model.models.data.build_model: class Sensor(SensorBase, TimestampMixin, table=True):
    registrations: list['Registration'] | None = Relationship(back_populates='sensors')
    sensornotes: list['SensorNote'] | None = Relationship(back_populates='sensors')
    deployments: list['Deployment'] | None = Relationship(back_populates='sensors')

2026-03-12 12:56:15,840 | DEBUG | fastapifromfrictionless.model.models.data.build_model: class SensorCreate(SensorBase):
    pass

2026-03-12 12:56:15,841 | DEBUG | fastapifromfrictionless.model.models.data.build_model: class SensorUpdate(SensorBase):
    macaddr: str | None
    name: str | None
    type: str | None
    status: str | None

2026-03-12 12:56:15,842 | DEBUG | fastapifromfrictionless.model.models.data.build_model: class SensorPublic(SensorBase):
    created_at: datetime
    updated_at: datetime

2026-03-12 12:56:15,843 | DEBUG | fastapifromfrictionless.model.models.data.build_model: class SensorPublicWithAll(SensorPublic):
    registrations: List['RegistrationPublic'] | None = None
    sensornotes: List['SensorNotePublic'] | None = None
    deployments: List['DeploymentPublic'] | None = None

2026-03-12 12:56:15,844 | INFO | fastapifromfrictionless.model.models.data.build: Building model for registration.schema.yaml
2026-03-12 12:56:15,849 | INFO | fastapifromfrictionless.model.models.data.build_model: Schema Registration foreign keys ['sensor_name']
2026-03-12 12:56:15,859 | DEBUG | fastapifromfrictionless.model.models.data.build_model: Registration not reference by DeploymentNote
2026-03-12 12:56:15,863 | DEBUG | fastapifromfrictionless.model.models.data.build_model: Registration not reference by SensorNote
2026-03-12 12:56:15,869 | DEBUG | fastapifromfrictionless.model.models.data.build_model: Registration not reference by Deployment
2026-03-12 12:56:15,869 | DEBUG | fastapifromfrictionless.model.models.data.build_model: Registration not reference by Deployment
2026-03-12 12:56:15,870 | DEBUG | fastapifromfrictionless.model.models.data.build_model: Registration not reference by Deployment
2026-03-12 12:56:15,870 | DEBUG | fastapifromfrictionless.model.models.data.build_model: Registration not reference by Deployment
2026-03-12 12:56:15,871 | INFO | fastapifromfrictionless.model.models.data.build_model: Registration not referenced by other schemas.
2026-03-12 12:56:15,872 | INFO | fastapifromfrictionless.model.models.data.build_model: Primary key is 'id'. Will add to table model with autoincrement.
2026-03-12 12:56:15,872 | INFO | fastapifromfrictionless.model.models.data.build_model: {'name': 'macaddr', 'type': 'string'} converted to macaddr: str | None
2026-03-12 12:56:15,874 | INFO | fastapifromfrictionless.model.models.data.build_model: {'name': 'reg_email', 'type': 'string', 'format': 'email'} converted to reg_email: EmailStr | None
2026-03-12 12:56:15,874 | INFO | fastapifromfrictionless.model.models.data.build_model: {'name': 'outside', 'type': 'boolean'} converted to outside: bool | None
2026-03-12 12:56:15,875 | INFO | fastapifromfrictionless.model.models.data.build_model: {'name': 'sensor_name', 'type': 'string'} converted to sensor_name: str | None = Field(foreign_key='sensor.name')
2026-03-12 12:56:15,877 | INFO | fastapifromfrictionless.model.models.data.build_model: {'name': 'public', 'type': 'boolean'} converted to public: bool | None
2026-03-12 12:56:15,878 | INFO | fastapifromfrictionless.model.models.data.build_model: {'name': 'latitude', 'type': 'number'} converted to latitude: float | None
2026-03-12 12:56:15,879 | INFO | fastapifromfrictionless.model.models.data.build_model: {'name': 'longitude', 'type': 'number'} converted to longitude: float | None
2026-03-12 12:56:15,879 | INFO | fastapifromfrictionless.model.models.data.build_model: {'name': 'owner_name', 'type': 'string'} converted to owner_name: str | None
2026-03-12 12:56:15,883 | INFO | fastapifromfrictionless.model.models.data.build_model: {'name': 'owner_email', 'type': 'string', 'format': 'email'} converted to owner_email: EmailStr | None
2026-03-12 12:56:15,885 | INFO | fastapifromfrictionless.model.models.data.build_model: {'name': 'smsalert_number', 'type': 'string'} converted to smsalert_number: str | None
2026-03-12 12:56:15,886 | DEBUG | fastapifromfrictionless.model.models.data.build_model: class RegistrationBase(SQLModel):
    macaddr: str | None
    reg_email: EmailStr | None
    outside: bool | None
    sensor_name: str | None = Field(foreign_key='sensor.name')
    public: bool | None
    latitude: float | None
    longitude: float | None
    owner_name: str | None
    owner_email: EmailStr | None
    smsalert_number: str | None

2026-03-12 12:56:15,888 | INFO | fastapifromfrictionless.model.models.data.build_model: class Registration(RegistrationBase, TimestampMixin, table=True):
    id: int | None = Field(default=None, primary_key=True)
    sensors: list['Sensor'] | None = Relationship(back_populates='registrations')

2026-03-12 12:56:15,889 | DEBUG | fastapifromfrictionless.model.models.data.build_model: class RegistrationCreate(RegistrationBase):
    pass

2026-03-12 12:56:15,891 | DEBUG | fastapifromfrictionless.model.models.data.build_model: class RegistrationUpdate(RegistrationBase):
    macaddr: str | None
    reg_email: EmailStr | None
    outside: bool | None
    sensor_name: str | None
    public: bool | None
    latitude: float | None
    longitude: float | None
    owner_name: str | None
    owner_email: EmailStr | None
    smsalert_number: str | None

2026-03-12 12:56:15,891 | DEBUG | fastapifromfrictionless.model.models.data.build_model: class RegistrationPublic(RegistrationBase):
    id: int
    created_at: datetime
    updated_at: datetime

2026-03-12 12:56:15,892 | DEBUG | fastapifromfrictionless.model.models.data.build_model: class RegistrationPublicWithAll(RegistrationPublic):
    sensors: List['SensorPublic'] | None = None

2026-03-12 12:56:15,893 | INFO | fastapifromfrictionless.model.models.data.build: Building model for deployment-note.schema.yaml
2026-03-12 12:56:15,898 | INFO | fastapifromfrictionless.model.models.data.build_model: Schema DeploymentNote foreign keys ['deployment_name']
2026-03-12 12:56:15,919 | DEBUG | fastapifromfrictionless.model.models.data.build_model: DeploymentNote not reference by Registration
2026-03-12 12:56:15,925 | DEBUG | fastapifromfrictionless.model.models.data.build_model: DeploymentNote not reference by SensorNote
2026-03-12 12:56:15,936 | DEBUG | fastapifromfrictionless.model.models.data.build_model: DeploymentNote not reference by Deployment
2026-03-12 12:56:15,937 | DEBUG | fastapifromfrictionless.model.models.data.build_model: DeploymentNote not reference by Deployment
2026-03-12 12:56:15,938 | DEBUG | fastapifromfrictionless.model.models.data.build_model: DeploymentNote not reference by Deployment
2026-03-12 12:56:15,939 | DEBUG | fastapifromfrictionless.model.models.data.build_model: DeploymentNote not reference by Deployment
2026-03-12 12:56:15,941 | INFO | fastapifromfrictionless.model.models.data.build_model: DeploymentNote not referenced by other schemas.
2026-03-12 12:56:15,942 | INFO | fastapifromfrictionless.model.models.data.build_model: Primary key is 'id'. Will add to table model with autoincrement.
2026-03-12 12:56:15,942 | INFO | fastapifromfrictionless.model.models.data.build_model: {'name': 'deployment_name', 'type': 'string', 'constraints': {'required': True}} converted to deployment_name: str = Field(default=None, foreign_key='deployment.name')
2026-03-12 12:56:15,943 | INFO | fastapifromfrictionless.model.models.data.build_model: {'name': 'date', 'type': 'date', 'constraints': {'required': True}} converted to date: date
2026-03-12 12:56:15,945 | INFO | fastapifromfrictionless.model.models.data.build_model: {'name': 'author', 'type': 'string', 'constraints': {'required': True}} converted to author: str
2026-03-12 12:56:15,946 | INFO | fastapifromfrictionless.model.models.data.build_model: {'name': 'note', 'type': 'string', 'constraints': {'required': True}} converted to note: str
2026-03-12 12:56:15,947 | DEBUG | fastapifromfrictionless.model.models.data.build_model: class DeploymentNoteBase(SQLModel):
    deployment_name: str = Field(default=None, foreign_key='deployment.name')
    date: date
    author: str
    note: str

2026-03-12 12:56:15,947 | INFO | fastapifromfrictionless.model.models.data.build_model: class DeploymentNote(DeploymentNoteBase, TimestampMixin, table=True):
    id: int | None = Field(default=None, primary_key=True)
    deployments: list['Deployment'] | None = Relationship(back_populates='deploymentnotes')

2026-03-12 12:56:15,948 | DEBUG | fastapifromfrictionless.model.models.data.build_model: class DeploymentNoteCreate(DeploymentNoteBase):
    pass

2026-03-12 12:56:15,949 | DEBUG | fastapifromfrictionless.model.models.data.build_model: class DeploymentNoteUpdate(DeploymentNoteBase):
    deployment_name: str | None
    date: date | None
    author: str | None
    note: str | None

2026-03-12 12:56:15,950 | DEBUG | fastapifromfrictionless.model.models.data.build_model: class DeploymentNotePublic(DeploymentNoteBase):
    id: int
    created_at: datetime
    updated_at: datetime

2026-03-12 12:56:15,951 | DEBUG | fastapifromfrictionless.model.models.data.build_model: class DeploymentNotePublicWithAll(DeploymentNotePublic):
    deployments: List['DeploymentPublic'] | None = None

2026-03-12 12:56:15,952 | INFO | fastapifromfrictionless.model.models.data.build: Building model for sensor-note.schema.yaml
2026-03-12 12:56:15,958 | INFO | fastapifromfrictionless.model.models.data.build_model: Schema SensorNote foreign keys ['sensor_name']
2026-03-12 12:56:15,976 | DEBUG | fastapifromfrictionless.model.models.data.build_model: SensorNote not reference by Registration
2026-03-12 12:56:15,980 | DEBUG | fastapifromfrictionless.model.models.data.build_model: SensorNote not reference by DeploymentNote
2026-03-12 12:56:15,987 | DEBUG | fastapifromfrictionless.model.models.data.build_model: SensorNote not reference by Deployment
2026-03-12 12:56:15,988 | DEBUG | fastapifromfrictionless.model.models.data.build_model: SensorNote not reference by Deployment
2026-03-12 12:56:15,989 | DEBUG | fastapifromfrictionless.model.models.data.build_model: SensorNote not reference by Deployment
2026-03-12 12:56:15,989 | DEBUG | fastapifromfrictionless.model.models.data.build_model: SensorNote not reference by Deployment
2026-03-12 12:56:15,990 | INFO | fastapifromfrictionless.model.models.data.build_model: SensorNote not referenced by other schemas.
2026-03-12 12:56:15,990 | INFO | fastapifromfrictionless.model.models.data.build_model: Primary key is 'id'. Will add to table model with autoincrement.
2026-03-12 12:56:15,991 | INFO | fastapifromfrictionless.model.models.data.build_model: {'name': 'sensor_name', 'type': 'string', 'constraints': {'required': True}} converted to sensor_name: str = Field(default=None, foreign_key='sensor.name')
2026-03-12 12:56:15,991 | INFO | fastapifromfrictionless.model.models.data.build_model: {'name': 'date', 'type': 'date', 'constraints': {'required': True}} converted to date: date
2026-03-12 12:56:15,992 | INFO | fastapifromfrictionless.model.models.data.build_model: {'name': 'author', 'type': 'string', 'constraints': {'required': True}} converted to author: str
2026-03-12 12:56:15,993 | INFO | fastapifromfrictionless.model.models.data.build_model: {'name': 'note', 'type': 'string', 'constraints': {'required': True}} converted to note: str
2026-03-12 12:56:15,994 | DEBUG | fastapifromfrictionless.model.models.data.build_model: class SensorNoteBase(SQLModel):
    sensor_name: str = Field(default=None, foreign_key='sensor.name')
    date: date
    author: str
    note: str

2026-03-12 12:56:15,994 | INFO | fastapifromfrictionless.model.models.data.build_model: class SensorNote(SensorNoteBase, TimestampMixin, table=True):
    id: int | None = Field(default=None, primary_key=True)
    sensors: list['Sensor'] | None = Relationship(back_populates='sensornotes')

2026-03-12 12:56:15,995 | DEBUG | fastapifromfrictionless.model.models.data.build_model: class SensorNoteCreate(SensorNoteBase):
    pass

2026-03-12 12:56:15,995 | DEBUG | fastapifromfrictionless.model.models.data.build_model: class SensorNoteUpdate(SensorNoteBase):
    sensor_name: str | None
    date: date | None
    author: str | None
    note: str | None

2026-03-12 12:56:15,996 | DEBUG | fastapifromfrictionless.model.models.data.build_model: class SensorNotePublic(SensorNoteBase):
    id: int
    created_at: datetime
    updated_at: datetime

2026-03-12 12:56:15,996 | DEBUG | fastapifromfrictionless.model.models.data.build_model: class SensorNotePublicWithAll(SensorNotePublic):
    sensors: List['SensorPublic'] | None = None

2026-03-12 12:56:15,996 | INFO | fastapifromfrictionless.model.models.data.build: Building model for contact.schema.yaml
2026-03-12 12:56:15,999 | INFO | fastapifromfrictionless.model.models.data.build_model: Schema Contact foreign keys []
2026-03-12 12:56:16,016 | DEBUG | fastapifromfrictionless.model.models.data.build_model: Contact not reference by Registration
2026-03-12 12:56:16,021 | DEBUG | fastapifromfrictionless.model.models.data.build_model: Contact not reference by DeploymentNote
2026-03-12 12:56:16,026 | DEBUG | fastapifromfrictionless.model.models.data.build_model: Contact not reference by SensorNote
2026-03-12 12:56:16,031 | DEBUG | fastapifromfrictionless.model.models.data.build_model: Contact not reference by Deployment
2026-03-12 12:56:16,032 | DEBUG | fastapifromfrictionless.model.models.data.build_model: Contact not reference by Deployment
2026-03-12 12:56:16,033 | DEBUG | fastapifromfrictionless.model.models.data.build_model: Contact not reference by Deployment
2026-03-12 12:56:16,034 | DEBUG | fastapifromfrictionless.model.models.data.build_model: Contact is referenced by Deployment
2026-03-12 12:56:16,034 | INFO | fastapifromfrictionless.model.models.data.build_model: Contact is referenced by ['Deployment']
2026-03-12 12:56:16,035 | INFO | fastapifromfrictionless.model.models.data.build_model: {'name': 'fullname', 'type': 'string', 'constraints': {'required': True}} converted to fullname: str = Field(primary_key = True)
2026-03-12 12:56:16,036 | INFO | fastapifromfrictionless.model.models.data.build_model: {'name': 'email', 'type': 'string'} converted to email: str | None

In [31]:
fastapifromfrictionless.app('data').build().save('app.py')

In [32]:
fastapifromfrictionless.database('data').build('test.db').save('database.py')

2026-03-12 12:56:18,387 | INFO | fastapifromfrictionless.database.database.data.__init__: Building database from schemas in folder data
2026-03-12 12:56:18,389 | INFO | fastapifromfrictionless.database.database.data.save: Saving database file to database.py

## Start the database

Run `fastapi dev app.py` from data folder.

## Create a skeleton excel document

In [33]:
fastapifromfrictionless.load.empty_excel('data', 'data/sensor_tracking_BLANK.xlsx')

2026-03-12 12:56:28,034 | INFO | fastapifromfrictionless.load.empty_excel: Writing empty excel file (data/sensor_tracking_BLANK.xlsx) based on schemas as data.
2026-03-12 12:56:28,041 | INFO | fastapifromfrictionless.load.empty_excel: Creating table: location Fields: ['address', 'zipcode', 'description', 'neighborhood', 'latitude', 'longitude']
2026-03-12 12:56:28,046 | INFO | fastapifromfrictionless.load.empty_excel: Creating table: hotspot Fields: ['macaddr', 'serialnum', 'status', 'ssid', 'password']
2026-03-12 12:56:28,050 | INFO | fastapifromfrictionless.load.empty_excel: Creating table: sensor Fields: ['macaddr', 'name', 'type', 'status']
2026-03-12 12:56:28,055 | INFO | fastapifromfrictionless.load.empty_excel: Creating table: registration Fields: ['id', 'macaddr', 'reg_email', 'outside', 'sensor_name', 'public', 'latitude', 'longitude', 'owner_name', 'owner_email', 'smsalert_number']
2026-03-12 12:56:28,060 | INFO | fastapifromfrictionless.load.empty_excel: Creating table: deployment-note Fields: ['id', 'deployment_name', 'date', 'author', 'note']
2026-03-12 12:56:28,065 | INFO | fastapifromfrictionless.load.empty_excel: Creating table: sensor-note Fields: ['id', 'sensor_name', 'date', 'author', 'note']
2026-03-12 12:56:28,068 | INFO | fastapifromfrictionless.load.empty_excel: Creating table: contact Fields: ['fullname', 'email', 'phone']
2026-03-12 12:56:28,074 | INFO | fastapifromfrictionless.load.empty_excel: Creating table: deployment Fields: ['name', 'sensor_name', 'sensor_index', 'start_date', 'end_date', 'location_address', 'contact_fullname', 'hotspot_macaddr']

In [34]:
import pandas as pd
pd.read_excel('data/sensor_tracking_BLANK.xlsx', sheet_name='deployment')

Empty DataFrame
Columns: [name, sensor_name, sensor_index, start_date, end_date, location_address, contact_fullname, hotspot_macaddr]
Index: []

## Manually input data

or shape it to match the schemas.

In [35]:
pd.read_excel('data/sensor_tracking.xlsx', sheet_name='deployment')

,name,sensor_name,sensor_index,start_date,end_date,location_address,contact_fullname,hotspot_macaddr
0,MORPC_003_01,MORPC_003,33763.0,2020-04-24,2022-03-03,1777 E Broad St,Garry Clarke,NaN
1,MORPC_003_01,MORPC_003,33763.0,2020-04-24,2022-03-03,1777 E Broad St,Garry Clarke,NaN
2,MORPC_003_01,MORPC_003,33763.0,2020-04-24,2022-03-03,1777 E Broad St,Chris McDonald,NaN
3,MORPC_006_00,MORPC_006,33773.0,2021-07-23,2021-08-06,7560 Smoky Row Rd,Austin Deschene,NaN
4,MORPC_006_01,MORPC_006,118637.0,2021-09-25,NaT,441 Nashoba Ave,Megan Fiscus,NaN
...,...,...,...,...,...,...,...,...
217,MORPC_OSU_019_00,MORPC_OSU_019,221311.0,2024-06-25,2024-07-12,7560 Smoky Row Rd,Austin Deschene,NaN
218,MORPC_OSU_020_00,MORPC_OSU_020,221303.0,2024-06-25,2024-07-12,7560 Smoky Row Rd,Austin Deschene,NaN
219,MORPC_OSU_021_00,MORPC_OSU_021,103370.0,2024-07-12,2024-07-26,7560 Smoky Row Rd,Austin Deschene,NaN
220,MORPC_OSU_022_00,MORPC_OSU_022,221309.0,2024-07-12,2024-07-26,7560 Smoky Row Rd,Austin Deschene,NaN
221,MORPC_OSU_023_00,MORPC_OSU_023,NaN,2024-07-12,2024-07-26,7560 Smoky Row Rd,Austin Deschene,NaN

## Create a package of the resource

In [36]:
package = fastapifromfrictionless.load.create_package('data', 'sensor_tracking.xlsx')

package.to_yaml('data/sensor_tracking.package.yaml')

2026-03-12 12:56:32,710 | INFO | fastapifromfrictionless.load.create_package: appending location.schema.yaml to package
2026-03-12 12:56:32,712 | INFO | fastapifromfrictionless.load.create_package: appending hotspot.schema.yaml to package
2026-03-12 12:56:32,713 | INFO | fastapifromfrictionless.load.create_package: appending sensor.schema.yaml to package
2026-03-12 12:56:32,715 | INFO | fastapifromfrictionless.load.create_package: appending registration.schema.yaml to package
2026-03-12 12:56:32,717 | INFO | fastapifromfrictionless.load.create_package: appending deployment-note.schema.yaml to package
2026-03-12 12:56:32,719 | INFO | fastapifromfrictionless.load.create_package: appending sensor-note.schema.yaml to package
2026-03-12 12:56:32,721 | INFO | fastapifromfrictionless.load.create_package: appending contact.schema.yaml to package
2026-03-12 12:56:32,724 | INFO | fastapifromfrictionless.load.create_package: appending deployment.schema.yaml to package
2026-03-12 12:56:32,726 | DEBUG | fastapifromfrictionless.load.create_package: Building package.
2026-03-12 12:56:32,727 | INFO | fastapifromfrictionless.load.create_package: Saving package to data/sensor_tracking.package.yaml

"name: sensor_tracking\nversion: 0.0.1\ncreated: '2026-03-12T12:56:32.727799'\nresources:\n  - name: location\n    type: table\n    path: sensor_tracking.xlsx\n    scheme: file\n    format: xlsx\n    mediatype: application/vnd.ms-excel\n    dialect:\n      excel:\n        sheet: location\n    schema: location.schema.yaml\n  - name: hotspot\n    type: table\n    path: sensor_tracking.xlsx\n    scheme: file\n    format: xlsx\n    mediatype: application/vnd.ms-excel\n    dialect:\n      excel:\n        sheet: hotspot\n    schema: hotspot.schema.yaml\n  - name: sensor\n    type: table\n    path: sensor_tracking.xlsx\n    scheme: file\n    format: xlsx\n    mediatype: application/vnd.ms-excel\n    dialect:\n      excel:\n        sheet: sensor\n    schema: sensor.schema.yaml\n  - name: registration\n    type: table\n    path: sensor_tracking.xlsx\n    scheme: file\n    format: xlsx\n    mediatype: application/vnd.ms-excel\n    dialect:\n      excel:\n        sheet: registration\n    schema: registration.schema.yaml\n  - name: deployment-note\n    type: table\n    path: sensor_tracking.xlsx\n    scheme: file\n    format: xlsx\n    mediatype: application/vnd.ms-excel\n    dialect:\n      excel:\n        sheet: deployment-note\n    schema: deployment-note.schema.yaml\n  - name: sensor-note\n    type: table\n    path: sensor_tracking.xlsx\n    scheme: file\n    format: xlsx\n    mediatype: application/vnd.ms-excel\n    dialect:\n      excel:\n        sheet: sensor-note\n    schema: sensor-note.schema.yaml\n  - name: contact\n    type: table\n    path: sensor_tracking.xlsx\n    scheme: file\n    format: xlsx\n    mediatype: application/vnd.ms-excel\n    dialect:\n      excel:\n        sheet: contact\n    schema: contact.schema.yaml\n  - name: deployment\n    type: table\n    path: sensor_tracking.xlsx\n    scheme: file\n    format: xlsx\n    mediatype: application/vnd.ms-excel\n    dialect:\n      excel:\n        sheet: deployment\n    schema: deployment.schema.yaml\n"

In [20]:
resource = package.get_resource('deployment-note')

## Update the data in the database from package.

The FastAPI is running on http://127.0.0.1:8000

See docs at http://127.0.0.1:8000/docs#/

In [37]:
fastapifromfrictionless.load.update_api_from_package('http://127.0.0.1:8000', package_file='data/sensor_tracking.package.yaml')

2026-03-12 12:56:48,571 | INFO | fastapifromfrictionless.load.update_api_from_package: Updating data from data/sensor_tracking.package.yaml for ['location', 'hotspot', 'sensor', 'registration', 'deployment-note', 'sensor-note', 'contact', 'deployment']
2026-03-12 12:56:48,572 | INFO | fastapifromfrictionless.load.update_api_from_package: Getting all data for location
2026-03-12 12:56:48,573 | DEBUG | fastapifromfrictionless.load.requests_get_all: Getting all from at http://127.0.0.1:8000/location/all
2026-03-12 12:56:48,575 | DEBUG | urllib3.connectionpool._new_conn: Starting new HTTP connection (1): 127.0.0.1:8000

2026-03-12 12:56:48,619 | DEBUG | urllib3.connectionpool._make_request: http://127.0.0.1:8000 "GET /location/all HTTP/1.1" 200 2
2026-03-12 12:56:48,621 | WARNING | fastapifromfrictionless.load.update_api_from_package: No data in location, using empty index.
2026-03-12 12:56:48,622 | INFO | fastapifromfrictionless.load.update_api_from_package: Loading or updating each row in location
2026-03-12 12:56:48,625 | DEBUG | chardet.charsetprober.feed: SHIFT_JIS Japanese prober hit error at byte 61
2026-03-12 12:56:48,626 | DEBUG | chardet.charsetprober.feed: EUC-JP Japanese prober hit error at byte 11
2026-03-12 12:56:48,627 | DEBUG | chardet.charsetprober.feed: GB2312 Chinese prober hit error at byte 61
2026-03-12 12:56:48,628 | DEBUG | chardet.charsetprober.feed: EUC-KR Korean prober hit error at byte 11
2026-03-12 12:56:48,630 | DEBUG | chardet.charsetprober.feed: CP949 Korean prober hit error at byte 61
2026-03-12 12:56:48,631 | DEBUG | chardet.charsetprober.feed: Big5 Chinese prober hit error at byte 11
2026-03-12 12:56:48,632 | DEBUG | chardet.charsetprober.feed: EUC-TW Taiwan prober hit error at byte 11
2026-03-12 12:56:48,633 | DEBUG | chardet.charsetprober.feed: Johab Korean prober hit error at byte 11
2026-03-12 12:56:48,686 | DEBUG | chardet.charsetprober.get_confidence: windows-1251 Russian confidence = 0.06316428145753311
2026-03-12 12:56:48,687 | DEBUG | chardet.charsetprober.get_confidence: KOI8-R Russian confidence = 0.04692033457217828
2026-03-12 12:56:48,687 | DEBUG | chardet.charsetprober.get_confidence: ISO-8859-5 Russian confidence = 0.05451441019459798
2026-03-12 12:56:48,687 | DEBUG | chardet.charsetprober.get_confidence: MacCyrillic Russian confidence = 0.06676511303759841
2026-03-12 12:56:48,688 | DEBUG | chardet.charsetprober.get_confidence: IBM866 Russian confidence = 0.04575285907930732
2026-03-12 12:56:48,688 | DEBUG | chardet.charsetprober.get_confidence: IBM855 Russian confidence = 0.05417524582352934
2026-03-12 12:56:48,689 | DEBUG | chardet.charsetprober.get_confidence: ISO-8859-7 Greek confidence = 0.11041313424594462
2026-03-12 12:56:48,689 | DEBUG | chardet.charsetprober.get_confidence: windows-1253 Greek confidence = 0.11195563895594199
2026-03-12 12:56:48,690 | DEBUG | chardet.charsetprober.get_confidence: ISO-8859-5 Bulgarian confidence = 0.05113929624560395
2026-03-12 12:56:48,690 | DEBUG | chardet.charsetprober.get_confidence: windows-1251 Bulgarian confidence = 0.061600806532492454
2026-03-12 12:56:48,691 | DEBUG | chardet.charsetprober.get_confidence: TIS-620 Thai confidence = 0.04962849077601263
2026-03-12 12:56:48,692 | DEBUG | chardet.charsetprober.get_confidence: ISO-8859-9 Turkish confidence = 0.07794065215040312
2026-03-12 12:56:48,692 | DEBUG | chardet.charsetprober.get_confidence: ISO-8859-8 Hebrew confidence = 0.0
2026-03-12 12:56:48,693 | DEBUG | chardet.charsetprober.get_confidence: ISO-8859-8 Hebrew confidence = 0.06892608197972076
2026-03-12 12:56:48,693 | DEBUG | chardet.charsetprober.get_confidence: ISO-8859-8 Hebrew confidence = 0.06778004261188693
2026-03-12 12:56:48,694 | DEBUG | chardet.universaldetector.close: no probers hit minimum threshold
2026-03-12 12:56:48,695 | DEBUG | chardet.universaldetector.close: utf-8  confidence = 0.010000000000000009
2026-03-12 12:56:48,695 | DEBUG | chardet.universaldetector.close: SHIFT_JIS Japanese confidence = 0.01
2026-03-12 12:56:48,696 | DEBUG | chardet.universaldetector.close: EUC-JP Japanese confidence = 0.01
2026-03-12 12:56:48,696 | DEBUG | chardet.universaldetector.close: GB2312 Chinese confidence = 0.01
2026-03-12 12:56:48,697 | DEBUG | chardet.universaldetector.close: EUC-KR Korean confidence = 0.01
2026-03-12 12:56:48,697 | DEBUG | chardet.universaldetector.close: CP949 Korean confidence = 0.01
2026-03-12 12:56:48,698 | DEBUG | chardet.universaldetector.close: Big5 Chinese confidence = 0.01
2026-03-12 12:56:48,699 | DEBUG | chardet.universaldetector.close: EUC-TW Taiwan confidence = 0.01
2026-03-12 12:56:48,699 | DEBUG | chardet.universaldetector.close: Johab Korean confidence = 0.01
2026-03-12 12:56:48,700 | DEBUG | chardet.universaldetector.close: windows-1251 Russian confidence = 0.06316428145753311
2026-03-12 12:56:48,701 | DEBUG | chardet.universaldetector.close: KOI8-R Russian confidence = 0.04692033457217828
2026-03-12 12:56:48,702 | DEBUG | chardet.universaldetector.close: ISO-8859-5 Russian confidence = 0.05451441019459798
2026-03-12 12:56:48,703 | DEBUG | chardet.universaldetector.close: MacCyrillic Russian confidence = 0.06676511303759841
2026-03-12 12:56:48,704 | DEBUG | chardet.universaldetector.close: IBM866 Russian confidence = 0.04575285907930732
2026-03-12 12:56:48,705 | DEBUG | chardet.universaldetector.close: IBM855 Russian confidence = 0.05417524582352934
2026-03-12 12:56:48,705 | DEBUG | chardet.universaldetector.close: ISO-8859-7 Greek confidence = 0.11041313424594462
2026-03-12 12:56:48,706 | DEBUG | chardet.universaldetector.close: windows-1253 Greek confidence = 0.11195563895594199
2026-03-12 12:56:48,707 | DEBUG | chardet.universaldetector.close: ISO-8859-5 Bulgarian confidence = 0.05113929624560395
2026-03-12 12:56:48,708 | DEBUG | chardet.universaldetector.close: windows-1251 Bulgarian confidence = 0.061600806532492454
2026-03-12 12:56:48,708 | DEBUG | chardet.universaldetector.close: TIS-620 Thai confidence = 0.04962849077601263
2026-03-12 12:56:48,709 | DEBUG | chardet.universaldetector.close: ISO-8859-9 Turkish confidence = 0.07794065215040312
2026-03-12 12:56:48,710 | DEBUG | chardet.universaldetector.close: ISO-8859-8 Hebrew confidence = 0.0
2026-03-12 12:56:48,711 | DEBUG | chardet.universaldetector.close: ISO-8859-8 Hebrew confidence = 0.06892608197972076
2026-03-12 12:56:48,712 | DEBUG | chardet.universaldetector.close: ISO-8859-8 Hebrew confidence = 0.06778004261188693
2026-03-12 12:56:48,713 | DEBUG | chardet.universaldetector.close: ISO-8859-1  confidence = 0.01
2026-03-12 12:56:48,714 | DEBUG | chardet.universaldetector.close: MacRoman  confidence = 0.0
2026-03-12 12:56:48,745 | DEBUG | fastapifromfrictionless.load.update_api_from_package: row: {'address': '106 S Wheatland Ave', 'zipcode': 43204, 'description': 'Private Residence', 'neighborhood': 'Hilltop', 'latitude': Decimal('39.9540023291524'), 'longitude': Decimal('-83.0612302698839')}
2026-03-12 12:56:48,746 | DEBUG | fastapifromfrictionless.load.update_api_from_package: Posting row: {'address': '106 S Wheatland Ave', 'zipcode': 43204, 'description': 'Private Residence', 'neighborhood': 'Hilltop', 'latitude': Decimal('39.9540023291524'), 'longitude': Decimal('-83.0612302698839')}
2026-03-12 12:56:48,747 | DEBUG | fastapifromfrictionless.load.requests_post: Posting {"address":"106 S Wheatland Ave","zipcode":43204,"description":"Private Residence","neighborhood":"Hilltop","latitude":39.9540023291524,"longitude":-83.0612302698839} to http://127.0.0.1:8000/location.
2026-03-12 12:56:48,748 | DEBUG | urllib3.connectionpool._new_conn: Starting new HTTP connection (1): 127.0.0.1:8000
2026-03-12 12:56:48,780 | DEBUG | urllib3.connectionpool._make_request: http://127.0.0.1:8000 "POST /location HTTP/1.1" 200 250
2026-03-12 12:56:48,781 | DEBUG | fastapifromfrictionless.load.requests_post: b'{"address":"106 S Wheatland Ave","zipcode":43204,"description":"Private Residence","neighborhood":"Hilltop","latitude":39.9540023291524,"longitude":-83.0612302698839,"created_at":"2026-03-12T16:56:48.752649","updated_at":"2026-03-12T16:56:48.752662"}'
2026-03-12 12:56:48,783 | DEBUG | fastapifromfrictionless.load.update_api_from_package: row: {'address': '111 Liberty Street', 'zipcode': 43215, 'description': 'Business', 'neighborhood': 'Brewery District', 'latitude': Decimal('39.95221'), 'longitude': Decimal('-82.999318')}
2026-03-12 12:56:48,784 | DEBUG | fastapifromfrictionless.load.update_api_from_package: Posting row: {'address': '111 Liberty Street', 'zipcode': 43215, 'description': 'Business', 'neighborhood': 'Brewery District', 'latitude': Decimal('39.95221'), 'longitude': Decimal('-82.999318')}
2026-03-12 12:56:48,784 | DEBUG | fastapifromfrictionless.load.requests_post: Posting {"address":"111 Liberty Street","zipcode":43215,"description":"Business","neighborhood":"Brewery District","latitude":39.95221,"longitude":-82.999318} to http://127.0.0.1:8000/location.
2026-03-12 12:56:48,786 | DEBUG | urllib3.connectionpool._new_conn: Starting new HTTP connection (1): 127.0.0.1:8000
2026-03-12 12:56:48,796 | DEBUG | urllib3.connectionpool._make_request: http://127.0.0.1:8000 "POST /location HTTP/1.1" 200 234
2026-03-12 12:56:48,798 | DEBUG | fastapifromfrictionless.load.requests_post: b'{"address":"111 Liberty Street","zipcode":43215,"description":"Business","neighborhood":"Brewery District","latitude":39.95221,"longitude":-82.999318,"created_at":"2026-03-12T16:56:48.789932","updated_at":"2026-03-12T16:56:48.789946"}'
2026-03-12 12:56:48,799 | DEBUG | fastapifromfrictionless.load.update_api_from_package: row: {'address': '1125 East Main St', 'zipcode': 43205, 'description': 'COTA Transfer Station', 'neighborhood': 'Old Town East', 'latitude': Decimal('39.957497'), 'longitude': Decimal('-82.96899')}
2026-03-12 12:56:48,800 | DEBUG | fastapifromfrictionless.load.update_api_from_package: Posting row: {'address': '1125 East Main St', 'zipcode': 43205, 'description': 'COTA Transfer Station', 'neighborhood': 'Old Town East', 'latitude': Decimal('39.957497'), 'longitude': Decimal('-82.96899')}
2026-03-12 12:56:48,801 | DEBUG | fastapifromfrictionless.load.requests_post: Posting {"address":"1125 East Main St","zipcode":43205,"description":"COTA Transfer Station","neighborhood":"Old Town East","latitude":39.957497,"longitude":-82.96899} to http://127.0.0.1:8000/location.
2026-03-12 12:56:48,802 | DEBUG | urllib3.connectionpool._new_conn: Starting new HTTP connection (1): 127.0.0.1:8000
2026-03-12 12:56:48,813 | DEBUG | urllib3.connectionpool._make_request: http://127.0.0.1:8000 "POST /location HTTP/1.1" 200 243
2026-03-12 12:56:48,815 | DEBUG | fastapifromfrictionless.load.requests_post: b'{"address":"1125 East Main St","zipcode":43205,"description":"COTA Transfer Station","neighborhood":"Old Town East","latitude":39.957497,"longitude":-82.96899,"created_at":"2026-03-12T16:56:48.805669","updated_at":"2026-03-12T16:56:48.805676"}'
2026-03-12 12:56:48,817 | DEBUG | fastapifromfrictionless.load.update_api_from_package: row: {'address': '122 E Whitter Street', 'zipcode': 43206, 'description': 'Private Residence', 'neighborhood': 'German Village', 'latitude': 0, 'longitude': 0}
2026-03-12 12:56:48,818 | DEBUG | fastapifromfrictionless.load.update_api_from_package: Posting row: {'address': '122 E Whitter Street', 'zipcode': 43206, 'description': 'Private Residence', 'neighborhood': 'German Village', 'latitude': 0, 'longitude': 0}
2026-03-12 12:56:48,820 | DEBUG | fastapifromfrictionless.load.requests_post: Posting {"address":"122 E Whitter Street","zipcode":43206,"description":"Private Residence","neighborhood":"German Village","latitude":0.0,"longitude":0.0} to http://127.0.0.1:8000/location.
2026-03-12 12:56:48,822 | DEBUG | urllib3.connectionpool._new_conn: Starting new HTTP connection (1): 127.0.0.1:8000
2026-03-12 12:56:48,836 | DEBUG | urllib3.connectionpool._make_request: http://127.0.0.1:8000 "POST /location HTTP/1.1" 200 231
2026-03-12 12:56:48,837 | DEBUG | fastapifromfrictionless.load.requests_post: b'{"address":"122 E Whitter Street","zipcode":43206,"description":"Private Residence","neighborhood":"German Village","latitude":0.0,"longitude":0.0,"created_at":"2026-03-12T16:56:48.826065","updated_at":"2026-03-12T16:56:48.826078"}'
2026-03-12 12:56:48,839 | DEBUG | fastapifromfrictionless.load.update_api_from_package: row: {'address': '1220 Striebel Rd', 'zipcode': 43227, 'description': 'NONE', 'neighborhood': 'Whitehall', 'latitude': 0, 'longitude': 0}
2026-03-12 12:56:48,840 | DEBUG | fastapifromfrictionless.load.update_api_from_package: Posting row: {'address': '1220 Striebel Rd', 'zipcode': 43227, 'description': 'NONE', 'neighborhood': 'Whitehall', 'latitude': 0, 'longitude': 0}
2026-03-12 12:56:48,841 | DEBUG | fastapifromfrictionless.load.requests_post: Posting {"address":"1220 Striebel Rd","zipcode":43227,"description":"NONE","neighborhood":"Whitehall","latitude":0.0,"longitude":0.0} to http://127.0.0.1:8000/location.
2026-03-12 12:56:48,843 | DEBUG | urllib3.connectionpool._new_conn: Starting new HTTP connection (1): 127.0.0.1:8000
2026-03-12 12:56:48,857 | DEBUG | urllib3.connectionpool._make_request: http://127.0.0.1:8000 "POST /location HTTP/1.1" 200 209
2026-03-12 12:56:48,859 | DEBUG | fastapifromfrictionless.load.requests_post: b'{"address":"1220 Striebel Rd","zipcode":43227,"description":"NONE","neighborhood":"Whitehall","latitude":0.0,"longitude":0.0,"created_at":"2026-03-12T16:56:48.847024","updated_at":"2026-03-12T16:56:48.847037"}'
2026-03-12 12:56:48,861 | DEBUG | fastapifromfrictionless.load.update_api_from_package: row: {'address': '1221 Chesapeake Ave', 'zipcode': 43212, 'description': "Local Business (Steven's Catering)", 'neighborhood': 'Grandview Heights', 'latitude': Decimal('39.991993'), 'longitude': Decimal('-83.03988')}
2026-03-12 12:56:48,862 | DEBUG | fastapifromfrictionless.load.update_api_from_package: Posting row: {'address': '1221 Chesapeake Ave', 'zipcode': 43212, 'description': "Local Business (Steven's Catering)", 'neighborhood': 'Grandview Heights', 'latitude': Decimal('39.991993'), 'longitude': Decimal('-83.03988')}
2026-03-12 12:56:48,863 | DEBUG | fastapifromfrictionless.load.requests_post: Posting {"address":"1221 Chesapeake Ave","zipcode":43212,"description":"Local Business (Steven's Catering)","neighborhood":"Grandview Heights","latitude":39.991993,"longitude":-83.03988} to http://127.0.0.1:8000/location.
2026-03-12 12:56:48,865 | DEBUG | urllib3.connectionpool._new_conn: Starting new HTTP connection (1): 127.0.0.1:8000
2026-03-12 12:56:48,879 | DEBUG | urllib3.connectionpool._make_request: http://127.0.0.1:8000 "POST /location HTTP/1.1" 200 262
2026-03-12 12:56:48,880 | DEBUG | fastapifromfrictionless.load.requests_post: b'{"address":"1221 Chesapeake Ave","zipcode":43212,"description":"Local Business (Steven\'s Catering)","neighborhood":"Grandview Heights","latitude":39.991993,"longitude":-83.03988,"created_at":"2026-03-12T16:56:48.869280","updated_at":"2026-03-12T16:56:48.869316"}'
2026-03-12 12:56:48,882 | DEBUG | fastapifromfrictionless.load.update_api_from_package: row: {'address': '1295 Glenn Ave', 'zipcode': 43212, 'description': 'Private Residence', 'neighborhood': 'Grandview Heights', 'latitude': Decimal('39.982983'), 'longitude': Decimal('-83.05434')}
2026-03-12 12:56:48,883 | DEBUG | fastapifromfrictionless.load.update_api_from_package: Posting row: {'address': '1295 Glenn Ave', 'zipcode': 43212, 'description': 'Private Residence', 'neighborhood': 'Grandview Heights', 'latitude': Decimal('39.982983'), 'longitude': Decimal('-83.05434')}
2026-03-12 12:56:48,884 | DEBUG | fastapifromfrictionless.load.requests_post: Posting {"address":"1295 Glenn Ave","zipcode":43212,"description":"Private Residence","neighborhood":"Grandview Heights","latitude":39.982983,"longitude":-83.05434} to http://127.0.0.1:8000/location.
2026-03-12 12:56:48,885 | DEBUG | urllib3.connectionpool._new_conn: Starting new HTTP connection (1): 127.0.0.1:8000
2026-03-12 12:56:48,892 | DEBUG | urllib3.connectionpool._make_request: http://127.0.0.1:8000 "POST /location HTTP/1.1" 200 240
2026-03-12 12:56:48,893 | DEBUG | fastapifromfrictionless.load.requests_post: b'{"address":"1295 Glenn Ave","zipcode":43212,"description":"Private Residence","neighborhood":"Grandview Heights","latitude":39.982983,"longitude":-83.05434,"created_at":"2026-03-12T16:56:48.887849","updated_at":"2026-03-12T16:56:48.887856"}'
2026-03-12 12:56:48,894 | DEBUG | fastapifromfrictionless.load.update_api_from_package: row: {'address': '133 S Cypress Ave', 'zipcode': 43222, 'description': 'Private Residence', 'neighborhood': 'Franklinton 4', 'latitude': 0, 'longitude': 0}
2026-03-12 12:56:48,895 | DEBUG | fastapifromfrictionless.load.update_api_from_package: Posting row: {'address': '133 S Cypress Ave', 'zipcode': 43222, 'description': 'Private Residence', 'neighborhood': 'Franklinton 4', 'latitude': 0, 'longitude': 0}
2026-03-12 12:56:48,896 | DEBUG | fastapifromfrictionless.load.requests_post: Posting {"address":"133 S Cypress Ave","zipcode":43222,"description":"Private Residence","neighborhood":"Franklinton 4","latitude":0.0,"longitude":0.0} to http://127.0.0.1:8000/location.
2026-03-12 12:56:48,897 | DEBUG | urllib3.connectionpool._new_conn: Starting new HTTP connection (1): 127.0.0.1:8000
2026-03-12 12:56:48,907 | DEBUG | urllib3.connectionpool._make_request: http://127.0.0.1:8000 "POST /location HTTP/1.1" 200 227
2026-03-12 12:56:48,908 | DEBUG | fastapifromfrictionless.load.requests_post: b'{"address":"133 S Cypress Ave","zipcode":43222,"description":"Private Residence","neighborhood":"Franklinton 4","latitude":0.0,"longitude":0.0,"created_at":"2026-03-12T16:56:48.899688","updated_at":"2026-03-12T16:56:48.899698"}'
2026-03-12 12:56:48,909 | DEBUG | fastapifromfrictionless.load.update_api_from_package: row: {'address': '1390 Cleveland Ave', 'zipcode': 43211, 'description': 'COTA Transfer Station', 'neighborhood': 'Linden', 'latitude': Decimal('39.993523'), 'longitude': Decimal('-82.98157')}
2026-03-12 12:56:48,910 | DEBUG | fastapifromfrictionless.load.update_api_from_package: Posting row: {'address': '1390 Cleveland Ave', 'zipcode': 43211, 'description': 'COTA Transfer Station', 'neighborhood': 'Linden', 'latitude': Decimal('39.993523'), 'longitude': Decimal('-82.98157')}
2026-03-12 12:56:48,910 | DEBUG | fastapifromfrictionless.load.requests_post: Posting {"address":"1390 Cleveland Ave","zipcode":43211,"description":"COTA Transfer Station","neighborhood":"Linden","latitude":39.993523,"longitude":-82.98157} to http://127.0.0.1:8000/location.
2026-03-12 12:56:48,911 | DEBUG | urllib3.connectionpool._new_conn: Starting new HTTP connection (1): 127.0.0.1:8000
2026-03-12 12:56:48,921 | DEBUG | urllib3.connectionpool._make_request: http://127.0.0.1:8000 "POST /location HTTP/1.1" 200 237
2026-03-12 12:56:48,922 | DEBUG | fastapifromfrictionless.load.requests_post: b'{"address":"1390 Cleveland Ave","zipcode":43211,"description":"COTA Transfer Station","neighborhood":"Linden","latitude":39.993523,"longitude":-82.98157,"created_at":"2026-03-12T16:56:48.914213","updated_at":"2026-03-12T16:56:48.914224"}'
2026-03-12 12:56:48,924 | DEBUG | fastapifromfrictionless.load.update_api_from_package: row: {'address': '1575 Studer Ave', 'zipcode': 43207, 'description': 'Private Residence', 'neighborhood': 'Far South', 'latitude': Decimal('39.93312'), 'longitude': Decimal('-82.96629')}
2026-03-12 12:56:48,924 | DEBUG | fastapifromfrictionless.load.update_api_from_package: Posting row: {'address': '1575 Studer Ave', 'zipcode': 43207, 'description': 'Private Residence', 'neighborhood': 'Far South', 'latitude': Decimal('39.93312'), 'longitude': Decimal('-82.96629')}
2026-03-12 12:56:48,925 | DEBUG | fastapifromfrictionless.load.requests_post: Posting {"address":"1575 Studer Ave","zipcode":43207,"description":"Private Residence","neighborhood":"Far South","latitude":39.93312,"longitude":-82.96629} to http://127.0.0.1:8000/location.
2026-03-12 12:56:48,926 | DEBUG | urllib3.connectionpool._new_conn: Starting new HTTP connection (1): 127.0.0.1:8000
2026-03-12 12:56:48,934 | DEBUG | urllib3.connectionpool._make_request: http://127.0.0.1:8000 "POST /location HTTP/1.1" 200 232
2026-03-12 12:56:48,935 | DEBUG | fastapifromfrictionless.load.requests_post: b'{"address":"1575 Studer Ave","zipcode":43207,"description":"Private Residence","neighborhood":"Far South","latitude":39.93312,"longitude":-82.96629,"created_at":"2026-03-12T16:56:48.928783","updated_at":"2026-03-12T16:56:48.928790"}'

TypeError: ValidationError.__new__() missing 2 required positional arguments: 'title' and 'line_errors'